print()
print(2+2)
print()
print(2-2)
print()
print(2*2)
print()
print(2/2)
print()
print(2//2)
print()
print(2%2)
print()
print(2**2)
print()
#exponentiation x to power y
print(2 ** 3)
print(2 ** 3.)
print(2. ** 3)
print(2. ** 3.)
print()
#multiplication
print(2 * 3)
print(2 * 3.)
print(2. * 3)
print(2. * 3.)
print()
#division
print(6 / 3)
print(6 / 3.)
print(6. / 3)
print(6. / 3.)
print()
#integer division rounds off the decimal
print(6 // 3)
print(6 // 3.)
print(6. // 3)
print(6. // 3.)
print()
#further explanation for these parts
print(6 // 4)
print(6. // 4)
print()
print(-6 // 4)
print(6. // -4)
print()
#remainder (modulo) it displays what was left
print(14 % 4)
print()
print(14 // 4)
print()
print(3 * 4)
print()
print(14 - 12 )
print()
print(12 % 4.5)
print()
#addition
print(-4 + 4)
print(-4. + 8)
print()
#subtraction operator, unary and binary operators
print(-4 - 4)
print(4. - 8)
print(-1.1)
print()
print(+2)
print()
#operators and their bindings
print(9 % 6 % 2)
print()
print(2 ** 2 ** 3)
print()
print(-3 ** 2)
print(-2 ** 3)
print(-(3 ** 2))
print()
print(2 * 3 % 5)
print()
print((5 * ((25 % 13) + 100) / (2 * 13)) // 2)
print()