print()
print("hello this is my first attempt")
print()
print("the itsy bitsy spider\nwent up the water spout")
print()
print("Out came the rain and", "washed the spider out")
print()

print()
print("My name is", "Python.", end=" ")
print("Mypython.")
print()

print()
print("out came the sun", "and washed out all the rain", sep="-", end="*")
print()
print("and the itsy bitsy spider", "went up the spout again", sep="*", end="*\n")
print()

print()
print("mary had a", "little lamb", "whose fleece was", sep="***", end="...")
print("white as snow")

print()
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()